### PR TITLE
Validates client url from client cookie.

### PR DESCRIPTION
**Pull request by DAN-BIWOTT**
Compares the url drawn from the client cookie against a white-list within the database.

### CODE REVIEW

**Comment by brandones** [comment]
What's the rationale for this?

**Comment by DAN-BIWOTT** [comment]
The white list can be made up of regex expressions or simple strings.
`<globalProperty>
      ...
^(htt(p|ps):\/\/)?(www\.)?A?a?mpath\.com(\/\d[0-9]\/[a-zA-Z]*)?,http://www.kimosabe.com
      ...
    </globalProperty>`  
After extracting the URL from the client browser,
Screenshot from 2020-03-12 09-48-44
It's compared against the predefined white list URLs. If it passes either the regex test or string test, The login importmap is made available.
Screenshot from 2020-03-12 09-57-02

**Comment by brandones** [comment]
Yes, I understand how it works. I mean, what is the rationale? Why did you implement this?

**Comment by DAN-BIWOTT** [comment]
The import map url is provided by the client, an added layer of security is
necessary. For instance, a client decides to change the import-map-url
within the cookies to "evil.co", this will result in single-spa downloading
the wrong javascript modules. Since we can't predict the nature of the
module and her behavior relative to the mother application, I found it
necessary to restrict the modules being pulled to the ones specified within
the database.

**Comment by brandones** [comment]
Well, the client wouldn't decide to do that to themselves. The only way I'm aware of that a client would be compromised in this way would be XSS. That is, in order for an attacker to change cookies or localStorage, they need to have arbitrary JS execution. At that point, the client is hosed. The attacker can download and execute whatever they want.

This is not my area of expertise; I'd appreciate a second opinion from @fatmali or @joeldenning 

If this seems like a good idea to one of them, then I'll review the code itself.

**Comment by internettrans** [comment]
I think this is a sensible security measure. One attack vector that this helps against is [self xss](https://en.wikipedia.org/wiki/Self-XSS).

A more comprehensive and important security measure for module-spa to take is CSP. I'd very highly recommend adding response headers for [Content Security Policy](https://developer.mozilla.org/en-US/docs/Web/HTTP/CSP). CSP is one of the most important security things any web app can add. With a proper CSP in place, this URL whitelist would actually be unnecessary since the browser would prevent the modules in the import map being loaded because they fail CSP.

**Comment by internettrans** [comment]
Also, somewhat related - I authored some new documentation about security of import map overrides at https://github.com/joeldenning/import-map-overrides#security

**Comment by dkayiwa** [comment]
@isears could you be having any comments on this?

**Comment by brandones** [comment]
@DAN-BIWOTT , would you be open to looking into implementing CSP instead?

**Comment by isears** [comment]
Thanks for the ping @dkayiwa 

Big fan of @joeldenning's suggestion to implement CSP over building a custom solution. Seems like the CSP approach would be both easier to maintain and more extensible.

**Comment by DAN-BIWOTT** [comment]
> @DAN-BIWOTT , would you be open to looking into implementing CSP instead?

I don't mind. It's a better approach. I'll start working on it.

**Comment by brandones** [comment]
Awesome, thank you so much for your work @DAN-BIWOTT . And thank you for the helpful advice, @joeldenning and @isears .

**Pull request closed without merging**
